import { Amiri } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";

const amiri = Amiri({
  variable: '--font-amiri',
  weight: ['400', '700'],
  subsets: ['arabic'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
      dir="rtl"
        className={`${amiri.className} relative top-24 antialiased -z-50 flex justify-around items-center  `}
      >
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
