import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
      dir="rtl"
        className={`${geistSans.variable} ${geistMono.variable} relative top-24 antialiased -z-50 flex justify-around items-center  `}
      >
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
